database:
  main:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: ""
    dbname: "movie_festival"
    sslmode: "disable"
    timezone: "Asia/Jakarta"
    encoding: "UTF8"
    debug: true

appport: :3000